### ISSUE TITLE
why no hjkl mappings?

### ISSUE THREAD

**Issue by ghost** [shawncplus/dotfiles#7]

**Comment by quizzmaster** [comment]
without any description, it's really hard to determine where you miss hjkl mappings.. For example the tmux config has hjkl mappings.

**Comment by ghost** [comment]
I mean the vim script files ,not tmux config .
And does the tumx config mapping work well for vim ?

**Comment by quizzmaster** [comment]
Why remap the movement keys? He only disabled the arrow keys and added the functionality to move lines with up and down in normal mode.
